language: python

python:
  - "3.8.2"

service:
  - postgresql

addons:
  postgresql: "12"

env:
  - DJANGO=3.0.6 DB=postgres

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE passKeeper;" -U postgres

script:
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 manage.py runserver
