language: python

python:
- 3.8.2

services:
- postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
- DJANGO=3.0.6 DB=postgres
#  global:
#  - PGPORT=5433

install:
- pip install -r requirements.txt

before_script:
# The default user for accessing the local PostgreSQL server is postgres with a blank password.
- psql -c 'create database passKeeper;' -U postgres

script:
- python3 -m venv venv
- source venv/bin/activate
- python3 manage.py runserver

# notifications:
#   email:
#     recipients:
#       - random@email.com
#     on_success: never
#     on_failure: always
