# Generated by Django 3.0.6 on 2020-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_safe_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
